CREATE DATABASE IF NOT EXISTS RESTAURANTE;
USE RESTAURANTE;

CREATE TABLE MESAS (
    IdMesa   INT AUTO_INCREMENT PRIMARY KEY,
    Numero   INT NOT NULL UNIQUE,
    Capacidad INT NOT NULL,
    Estado   VARCHAR(15) NOT NULL DEFAULT 'LIBRE'
);

CREATE TABLE PLATOS (
    IdPlato INT AUTO_INCREMENT PRIMARY KEY,
    Nombre  VARCHAR(100) NOT NULL,
    Precio  NUMERIC(10,2) NOT NULL
);

CREATE TABLE PEDIDOS (
    IdPedido INT AUTO_INCREMENT PRIMARY KEY,
    IdMesa   INT NOT NULL,
    Fecha    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Estado   VARCHAR(15) NOT NULL DEFAULT 'ABIERTO',
    CONSTRAINT FK_PEDIDOS_MESAS FOREIGN KEY (IdMesa) REFERENCES MESAS (IdMesa)
);

CREATE TABLE DETALLE_PEDIDO (
    IdDetalle INT AUTO_INCREMENT PRIMARY KEY,
    IdPedido  INT NOT NULL,
    IdPlato   INT NOT NULL,
    Cantidad  INT NOT NULL,
    CONSTRAINT FK_DETALLE_PEDIDOS FOREIGN KEY (IdPedido) REFERENCES PEDIDOS (IdPedido),
    CONSTRAINT FK_DETALLE_PLATOS FOREIGN KEY (IdPlato) REFERENCES PLATOS (IdPlato)
);

INSERT INTO MESAS (Numero, Capacidad) VALUES (1, 4), (2, 2), (3, 6);
INSERT INTO PLATOS (Nombre, Precio) VALUES
('Casado con pollo', 4500), ('Ensalada Cesar', 3800), ('Refresco natural', 1200);
